package com.github.zopnote.soulsmagic.api.item.complex;

public enum Complex {
  SOUL_BLOOD,
  SOUL_SWORD,
  PURE_FIRE,
  PURE_GRAVITATION,
  PURE_WEATHER,

  MAGIC_STAFF_FIRE,
  MAGIC_STAFF_WEATHER,
  MAGIC_STAFF_GRAVITATION,
  MAGIC_STAFF_REALITY,
  MAGIC_STAFF_NONE,
  NONE
}
